#Ejercicio: nivel 3

print("Integer")
print(10)
print("Float")
print(9.8)
print("Complex")
print(4-4j)
print("String")
print("Alison")
print("Bolean")
print(3==3)
print(3>=4)
print("List")
print(["Azul", "Amarillo", "Rojo"])
print("Tuple")
print((1.4, 3.14, 7.9))
print("Dictionary")
print({"Nombre" : "Alison"})